### PR TITLE
Refractor code and add support for deleting jira issues that are not reported on snyk

### PR DESCRIPTION
**Pull request by AjayJagan**
This is an update to the code which has a few changes
- convert exclude_files.json to be an array of paths to ignore
- Add support to close jiras(if already present) which are no longer reported by snyk. 
- Adds a message "Closing this issue as it is no longer reported in snyk" in the jira while closing
- Add support to configure severity from cmd

### CODE REVIEW

**Comment by StevenTobin** [comment]
I'm getting an error on

`text: The value 'Kueue' does not exist for the field 'component'`

I can confirm that the component Kueue does not seem to exist in JIRA.

**Comment by AjayJagan** [comment]
> config/jira_components_mapping.json

thanks @StevenTobin , will take a look and fix it

**Comment by AjayJagan** [comment]
Hi @StevenTobin , I ran the script and I was able to run it successfully 🤔 
`INFO:root:Total number of issues created is: 147`
Could you please let me know the steps that you took to get the error.

**Comment by StevenTobin** [comment]
I just installed the requirements of pysnyk and jira and then ran `python jira-automation.py`

**Comment by StevenTobin** [comment]
After rebase I was able to run to completion.

/lgtm

**Pull request merged**
